apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  strategy: {}
  template:
    metadata:
      labels:
        app: account-service
        support: rocketchat
    spec:
      initContainers:
        - name: check-nats-ready
          image: busybox:latest
          command: ['sh', '-c', 'until nc -vz nats 4222; do echo "Waiting for nats service"; sleep 2; done;']
      containers:
        - name: account-service
          image: rocketchat/account-service:latest
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/rocketchat?replicaSet=rs0
            - name: TRANSPORTER
              value: nats://nats:4222
          ports:
            - name: http
              containerPort: 3000
            - name: tcp
              containerPort: 9458
          resources: {}
      restartPolicy: Always
status: {}
