apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
  labels:
    app: authorization
  annotations:
    kots.io/exclude: '{{repl eq (LicenseFieldValue "licenseType") "community" }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization
  strategy: {}
  template:
    metadata:
      labels:
        app: authorization
        support: rocketchat
    spec:
      initContainers:
        - name: check-nats-ready
          image: busybox:latest
          command: ['sh', '-c', 'until nc -vz nats 4222; do echo "Waiting for nats service"; sleep 2; done;']
      containers:
        - name: authorization
          image: rocketchat/authorization-service:{{repl ConfigOption "version_tag" }}
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/rocketchat?replicaSet=rs0
            - name: TRANSPORTER
              value: nats://nats:4222
          ports:
            - name: http
              containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
