apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
  labels:
    app: authorization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization
  strategy: {}
  template:
    metadata:
      labels:
        app: authorization
    spec:
      # initContainers:
      #   - name: init-mongo
      #     image: cloudfive/mongo-oplog
      #     command: ['sh', '-c',
      #       "for i in `seq 1 30`; do
      #         mongo mongo/rocketchat --eval \"
      #           rs.initiate({
      #             _id: 'rs0',
      #             members: [ { _id: 0, host: 'mongo:27017' } ]})\" &&
      #         s=$$? && break || s=$$?;
      #         echo \"Tried $$i times. Waiting 5 secs...\";
      #         sleep 5;
      #       done; (exit $$s)"
      #             ]
      containers:
        - name: authorization
          image: rocketchat/authorization-service:latest
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/rocketchat?replicaSet=rs0
            - name: TRANSPORTER
              value: nats://nats:4222
          ports:
            - name: http
              containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
