apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: rocketchat-config
spec:
  groups:
    - name: rocketchat
      title: RocketChat Settings
      description: Configuration for RocketChat
      items:
        - name: use_ingress
          title: Use Ingress?
          help_text: Include an Ingress object
          type: bool
          default: "1"
        - name: rocketchat_dns_hostname
          type: text
          title: RocketChat DNS Hostname
          help_text: RocketChat DNS Hostname eg.(rocketchat.example.com)
          default: "rocketchat.example.com"
          required: true
    - name: mongo
      title: MongoDB Settings
      description: Configuration for MongoDB
      items:
        - name: mongo_root_password
          type: password
          title: MongoDB Root Password
          default: "thisissapassword"
          required: true
        - name: mongo_rocketchat_password
          type: password
          title: MongoDB RocketChat Password
          default: "thisissapassword"
          required: true
        - name: mongo_volume_size
          type: text
          title: MongoDB Volume Size
          description: Size of the volume attached to the MongoDB pod. Unit is GB(eg. 100 = 100GB) 
          default: "100"
          required: true
