apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: rocketchat-config
spec:
  groups:
    - name: rocketchat
      title: RocketChat Settings
      description: Configuration for RocketChat
      items:
        - name: use_ingress
          title: Use Ingress?
          help_text: Include an Ingress object
          type: bool
          default: "1"
        - name: rocketchat_dns_hostname
          type: text
          title: RocketChat DNS Hostname
          help_text: RocketChat DNS Hostname eg.(rocketchat.example.com)
          default: "rocketchat.example.com"
          required: true
        - name: streamer_replicas
          type: text
          title: DDP Streamer replicas
          description: Number of DDP Streamer replicas ( ~1 per 500 concurrent users ).
          default: "1"
          required: true
        - name: use_presence
          title: Run the User Presence service?
          description: Choose whether to run the User Presence service.
          help_text: With a huge amount of data/users, turning this service off will avoid processing bottlenecks. If this service is off, the user online/offline status and notifications will not work properly.
          type: bool
          default: "1"
        - name: rocketchat_enterprise_license
          title: Enterprise License Token
          description: Please enter your Enterprise License.
          help_text: A valid license is needed to run RocketChat in enterprise mode.
          type: textarea
          required: true
    - name: mongo
      title: MongoDB Settings
      description: Configuration for MongoDB
      items:
        - name: mongo_root_password
          type: password
          title: MongoDB Root Password
          default: "thisissapassword"
          required: true
        - name: mongo_rocketchat_password
          type: password
          title: MongoDB RocketChat Password
          default: "thisissapassword"
          required: true
        - name: mongo_volume_size
          type: text
          title: MongoDB Volume Size
          description: Size of the volume attached to the MongoDB pod. Unit is GB(eg. 100 = 100GB) 
          default: "100"
          required: true
