apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: rocketchat-config
spec:
  groups:
    - name: rocketchat
      title: RocketChat Settings
      description: Configuration for RocketChat
      items:
          # I was told it's better to not allow user to touch that option, 
          # and maybe making this a licence field... And so I did. 
        # - name: use_microservices
        #   title: Enable micro-services? 
        #   help_text: Splits Rocket.Chat auxiliary services into different containers, thus improving scalability
        #   type: bool
        #   hidden: true
        - name: use_ingress
          title: Use Ingress?
          help_text: Include an Ingress object
          type: bool
          default: "1"
          # There's no good reason to disable Ingress, so 
          # it is possible that this option will be soon
          # removed from here, or, perhaps, kept for 
          # internal usage. 
          hidden: true
        - name: use_tls
          when: '{{repl and (ConfigOptionEquals "use_ingress" "1") (not IsKurl) }}' # kURL handles this
          title: Use TLS?
          help_text: Include a Secret object containing Certificate and it's Private Key
          type: bool
          default: "1"
        - name: node_port
          title: Node port
          when: '{{repl and (ConfigOptionEquals "use_ingress" "0") }}'
          help_text: Specify a Node Port for the service to be exposed, when not using Ingress
          type: text
          default: "30000"
    - name: certs
      title: TLS Configuration
      when: '{{repl and (ConfigOptionEquals "use_tls" "1") (ConfigOptionEquals "use_ingress" "1") (not IsKurl)}}'
      items:
      - name: tls_certificate_file
        title: Certificate
        type: file
      - name: tls_private_key_file
        title: Private Key
        type: file
    - name: mongo
      title: MongoDB Settings
      description: Configuration for MongoDB
      items:
        - name: mongo_type
          title: mongodb server
          type: select_one
          default: embedded_mongodb
          items:
            - name: embedded_mongodb
              title: Use embedded mongodb server
              help_text: Run a embedded mongodb server along with your rocketchat installation
            - name: external_mongodb
              title: Use external mongodb server
              help_text: Use an existing mongodb server for your deployment

        - name: mongo_root_password
          when: '{{repl ConfigOptionEquals "mongo_type" "embedded_mongodb"}}'
          value: "{{repl RandomString 20}}"
          type: password
          title: MongoDB Root Password
          required: true
          hidden: true
        - name: mongo_rocketchat_password
          when: '{{repl ConfigOptionEquals "mongo_type" "embedded_mongodb"}}'
          value: "{{repl RandomString 20}}"
          type: password
          title: MongoDB RocketChat Password
          required: true
          hidden: true
        - name: mongo_external_url
          when: '{{repl ConfigOptionEquals "mongo_type" "external_mongodb"}}'
          type: password
          title: MongoDB External URL
          default: "mongodb://user:password@localhost:27017/rocketchat"
          required: true
        - name: mongo_external_oplog_url
          when: '{{repl ConfigOptionEquals "mongo_type" "external_mongodb"}}'
          type: password
          title: MongoDB External Oplog URL
          default: "mongodb://user:password@localhost:27017/local?replicaSet=rs0&authSource=admin"
          required: true
    - name: monitoring
      title: Monitoring Configuration
      description: Configuration for Prometheus and Grafana
      items:
        - name: prometheus_type
          title: prometheus server
          type: select_one
          default: embedded_prometheus
          hidden: true # disable the option for external prometheus for now
          items:
            - name: embedded_prometheus
              title: Use embedded prometheus server
              help_text: Run a embedded prometheus server along with your rocketchat installation
            - name: external_prometheus
              title: Use external prometheus server
              help_text: Use an existing prometheus server for your deployment
        - name: prometheus_external_url
          when: '{{repl ConfigOptionEquals "prometheus_type" "external_prometheus"}}'
          type: text
          title: External Prometheus URL
          default: ""
          required: true
        - name: deploy_grafana
          title: Deploy grafana?
          help_text: Include a Grafana instance for metrics visualization
          type: bool
          default: "1"
        - name: grafana_user
          when: '{{repl ConfigOptionEquals "deploy_grafana" "1"}}'
          type: text
          title: Grafana username
          default: "admin"
          required: true
        - name: grafana_password
          when: '{{repl ConfigOptionEquals "deploy_grafana" "1"}}'
          type: password
          title: Grafana password
          default: "admin"
          required: true
        

