apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: rocketchat-config
spec:
  groups:
    - name: rocketchat
      title: RocketChat Settings
      description: Configuration for RocketChat
      items:
        - name: use_ingress
          title: Use Ingress?
          help_text: Include an Ingress object
          type: bool
          default: "1"
        - name: use_tls
          title: Use TLS certificates?
          help_text: Include a Secret object containing Certificate and it's Private Key
          type: bool
          default: "1"
        - name: certs
          title: TLS Configuration
          when: '{{repl ConfigOptionEquals "use_tls" "1"}}'
          items:
          - name: tls_private_key_file
            title: Private Key
            type: file
          - name: tls_certificate_file
            title: Certificate
            type: file
    - name: mongo
      title: MongoDB Settings
      description: Configuration for MongoDB
      items:
        - name: mongo_type
          title: mongodb server
          type: select_one
          default: embedded_mongodb
          items:
            - name: embedded_mongodb
              title: Use embedded mongodb server
              help_text: Run a embedded mongodb server along with your rocketchat installation
            - name: external_mongodb
              title: Use external mongodb server
              help_text: Use an existing mongodb server for your deployment

        - name: mongo_root_password
          when: '{{repl ConfigOptionEquals "mongo_type" "embedded_mongodb"}}'
          type: password
          title: MongoDB Root Password
          default: "thisissapassword"
          required: true
        - name: mongo_rocketchat_password
          when: '{{repl ConfigOptionEquals "mongo_type" "embedded_mongodb"}}'
          type: password
          title: MongoDB RocketChat Password
          default: "thisissapassword"
          required: true
        - name: mongo_external_url
          when: '{{repl ConfigOptionEquals "mongo_type" "external_mongodb"}}'
          type: password
          title: MongoDB External URL
          default: "mongodb://user:password@localhost:27017/rocketchat"
          required: true
        - name: mongo_external_oplog_url
          when: '{{repl ConfigOptionEquals "mongo_type" "external_mongodb"}}'
          type: password
          title: MongoDB External Oplog URL
          default: "mongodb://user:password@localhost:27017/local?replicaSet=rs0&authSource=admin"
          required: true

