apiVersion: v1
type: kubernetes.io/tls
kind: Secret
metadata:
  annotations:
    kots.io/exclude: '{{repl ConfigOptionEquals "deploy_grafana" "0"}}'
  name: grafana-admin
stringData:
  admin-user: '{{repl ConfigOption "grafana_user" }}'
  admin-password: '{{repl ConfigOption "grafana_password" }}'

