apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: mongo-volumeclaim
  name: mongo-volumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10000Mi
status: {}
