apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    service: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: mongo
        support: rocketchat
    spec:
      containers:
        - name: mongo
          image: cloudfive/mongo-oplog
          env:
          - name: HOSTNAME
            value: mongo
          - name: REPLICA_SET_NAME
            value: "rs0"
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volumeclaim
      restartPolicy: Always
      volumes:
        - name: mongo-volumeclaim
          persistentVolumeClaim:
            claimName: mongo-volumeclaim
status: {}
