apiVersion: v1
kind: Service
metadata:
  name: nats
  labels:
    app: nats
  annotations:
    kots.io/exclude: '{{repl eq (LicenseFieldValue "licenseType") "community" }}'
spec:
  ports:
    - name: "4222"
      port: 4222
      targetPort: 4222
  selector:
    app: nats