apiVersion: apps/v1
kind: Deployment
metadata:
  name: presence-service
  labels:
    app: presence-service
  annotations:
    kots.io/when: '{{repl ConfigOptionEquals "use_presence" "1" }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presence-service
  strategy: {}
  template:
    metadata:
      labels:
        app: presence-service
        support: rocketchat
    spec:
      initContainers:
        - name: check-nats-ready
          image: busybox:latest
          command: ['sh', '-c', 'until nc -vz nats 4222; do echo "Waiting for nats service"; sleep 2; done;']
      containers:
        - name: presence-service
          image: rocketchat/presence-service:latest
          env:
            - name: TRANSPORTER
              value: nats://nats:4222
            - name: MONGO_URL
              value: mongodb://mongo:27017/rocketchat?replicaSet=rs0
          ports:
            - name: http
              containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
