apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: '{{repl Namespace}}'
  name: rocketchat-prometheus
  annotations:
    kots.io/exclude: '{{repl ConfigOptionEquals "prometheus_type" "external_prometheus"}}'
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
---
#### This is being used mostly for kube-state-metrics
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: '{{repl Namespace}}'
  name: rocketchat-prometheus
  annotations:
    kots.io/exclude: '{{repl ConfigOptionEquals "prometheus_type" "external_prometheus"}}'
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile 
rules:
  - apiGroups:
      - ""
      - extensions
      - apps
      - batch
    resources:
      - nodes
      - nodes/metrics
      - nodes/proxy
      - deployments
      - deployments/metrics
      - statefulsets
      - daemonsets
      - cronjobs
      - replicasets
      - replicationcontrollers
      - jobs
      - resourcequotas
      - limitranges
      - persistentvolumeclaims
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rocketchat-prometheus
  namespace: '{{repl Namespace}}'
  annotations:
    kots.io/exclude: '{{repl ConfigOptionEquals "prometheus_type" "external_prometheus"}}'
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rocketchat-prometheus
subjects:
- kind: ServiceAccount
  name: rocketchat-prometheus
  namespace: '{{repl Namespace}}'
