apiVersion: v1
kind: Service
metadata:
  name: rocketchat-prometheus
  annotations:
    kots.io/exclude: '{{repl ConfigOptionEquals "prometheus_type" "external_prometheus"}}'
spec:
  selector: 
    app: rocketchat-prometheus
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090 