apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kots.io/when: '{{repl and (ConfigOptionEquals "use_ingress" "1") (not IsKurl) }}'
spec:
  rules:
  - host: "repl{{ LicenseFieldValue `license_url`}}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rocketchat-rocketchat
            port:
              number: 80
