apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat
  labels:
    app: rocketchat
  annotations:
    kots.io/when: '{{repl eq (LicenseFieldValue "licenseType") "community" }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat
  strategy: {}
  template:
    metadata:
      labels:
        app: rocketchat
        support: rocketchat
    spec:
      initContainers:
        - name: init-mongo
          image: cloudfive/mongo-oplog
          command: ['sh', '-c',
            "for i in `seq 1 30`; do
              mongo mongo/rocketchat --eval \"
                rs.initiate({
                  _id: 'rs0',
                  members: [ { _id: 0, host: 'mongo:27017' } ]})\" &&
              s=$$? && break || s=$$?;
              echo \"Tried $$i times. Waiting 5 secs...\";
              sleep 5;
            done; (exit $$s)"
                  ]
      containers:
        - name: rocketchat
          image: rocketchat/rocket.chat:{{repl ConfigOption "version_tag" }}
          env:
            - name: MONGO_OPLOG_URL
              value: mongodb://mongo:27017/local
            - name: MONGO_URL
              value: mongodb://mongo:27017/rocketchat?replicaSet=rs0
          ports:
            - name: http
              containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
