apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kots.io/when: '{{repl ConfigOptionEquals "use_ingress" "1" }}'
    projectcontour.io/websocket-routes: /sockjs
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rocketchat
            port:
              number: 3000
      - path: /sockjs
        pathType: Prefix
        backend:
          service:
            name: ddp-streamer
            port:
              number: 3000
