apiVersion: v1
kind: Service
metadata:
  name: rocketchat
  labels:
    app: rocketchat
spec:
  type: 'repl{{ if IsKurl }}ClusterIPrepl{{else}}NodePortrepl{{end}}'
  ports:
    - name: "web"
      port: 3000
      targetPort: 3000
  selector:
    app: rocketchat
status:
  loadBalancer: {}