apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: rocketchat
spec:
  image: quay.io/prometheus/prometheus:v2.24.0
  listenLocal: false
  logFormat: logfmt
  logLevel: info
  paused: false
  podMonitorSelector:
    matchLabels:
      app: rocketchat
  portName: web
  replicas: 2
  retention: 15d
  routePrefix: /
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: rocketchat-prometheus-operator
  serviceMonitorSelector:
    matchLabels:
      app: rocketchat
  shards: 1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: default
  version: v2.24.0
