apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rocketchat
  labels:
    app: rocketchat
spec:
  selector:
    matchLabels:
      app: rocketchat
  endpoints:
  - port: web
