apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat
  labels:
    app: rocketchat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat
  strategy: {}
  template:
    metadata:
      labels:
        app: rocketchat
        support: rocketchat
    spec:
      initContainers:
        - name: init-mongo
          image: cloudfive/mongo-oplog
          command: ['sh', '-c',
            "for i in `seq 1 30`; do
              mongo mongo/rocketchat --eval \"
                rs.initiate({
                  _id: 'rs0',
                  members: [ { _id: 0, host: 'mongo:27017' } ]})\" &&
              s=$$? && break || s=$$?;
              echo \"Tried $$i times. Waiting 5 secs...\";
              sleep 5;
            done; (exit $$s)"
                  ]
      containers:
        - name: rocketchat
          image: rocketchat/rocket.chat:latest
          env:
            - name: MONGO_OPLOG_URL
              value: mongodb://mongo:27017/local
            - name: MONGO_URL
              value: mongodb://mongo:27017/rocketchat?replicaSet=rs0
            - name: TRANSPORTER
              value: nats://nats:4222
            - name: ROCKETCHAT_LICENSE
              value: '{{repl LicenseFieldValue "rocketchat_enterprise_license" }}'
            - name: DISABLE_DB_WATCH
              value: 'true'
            - name: DISABLE_PRESENCE_MONITOR
              value: 'true'
            - name: INTERNAL_SERVICES_ONLY
              value: 'true'
            - name: ROOT_URL
              value: '{{repl LicenseFieldValue "license_url" }}'
            - name: OVERWRITE_SETTING_Site_Url
              value: '{{repl LicenseFieldValue "license_url" }}'
          ports:
            - name: http
              containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
