apiVersion: v1
type: kubernetes.io/tls
kind: Secret
metadata:
  name: rocketchat-tls
data:
  tls.crt: '{{repl ConfigOption "tls_certificate_file" }}'
  tls.key: '{{repl ConfigOption "tls_private_key_file" }}'

