apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kots.io/when: '{{repl and (ConfigOptionEquals "use_ingress" "1") IsKurl }}'
    projectcontour.io/websocket-routes: /sockjs,/websocket
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rocketchat
            port:
              number: 80