apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: rocketchat-ingressroute
  annotations:
    kots.io/when: '{{repl and (ConfigOptionEquals "use_ingress" "1") (IsKurl)}}'
spec:
  virtualhost:
    fqdn: "repl{{ LicenseFieldValue `license_url`}}"
  routes:
    - match: /
      services:
        - name: rocketchat-rocketchat
          port: 80
    - match: /sockjs
      enableWebsockets: true
      services:
        - name: rocketchat-ddp-streamer
          port: 80
    - match: /websock
      enableWebsockets: true
      services:
        - name: rocketchat-ddp-streamer
          port: 80