apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rocketchat
  namespace: monitoring
  labels:
    app: rocketchat
spec:
  namespaceSelector:
    matchNames:
      - '{{repl Namespace }}'
  selector:
    matchLabels:
      app: rocketchat
  endpoints:
  - port: prometheus
