apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: rocketchat
spec:
  chart:
    name: rocketchat
    chartVersion: 3.1.0
  values:
    mongodb:
      auth:
        username: rocketchat
        password: "repl{{ ConfigOption `mongo_rocketchat_password`}}"
        database:  rocketchat
        rootPassword: "repl{{ ConfigOption `mongo_root_password`}}"
  useHelmInstall: true
