apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-hub
  labels:
    app: stream-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-hub
  strategy: {}
  template:
    metadata:
      labels:
        app: stream-hub
        support: rocketchat
    spec:
      initContainers:
        - name: check-nats-ready
          image: busybox:latest
          command: ['sh', '-c', 'until nc -vz nats 4222; do echo "Waiting for nats service"; sleep 2; done;']
      containers:
        - name: stream-hub
          image: rocketchat/stream-hub-service:latest
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/rocketchat?replicaSet=rs0
            - name: TRANSPORTER
              value: nats://nats:4222
          ports:
            - name: http
              containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
