apiVersion: troubleshoot.replicated.com/v1beta1
kind: SupportBundle
metadata:
  name: rocketchat-support-bundle
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        selector:
          - app.kubernetes.io/name=rocketchat
        limits:
          maxAge: 720h
          maxLines: 1000
    - http:
        name: api-info
        get:
          url: "http://rocketchat-rocketchat/api/info"
    - exec:
        name: mongo-version
        selector:
          - service=mongo
        command: ["mongo"]
        args: ["--eval", "db.version()"]
        timeout: 5s
    - run:
        name: ping
        collectorName: "ping-google"
        image: busybox:1
        namespace: default
        command: ["ping"]
        args: ["-w", "5", "www.google.com"]
        imagePullPolicy: IfNotPresent
    - run:
        name: ping
        collectorName: "ping-google-dns-ip"
        image: busybox:1
        namespace: default
        command: ["ping"]
        args: ["-w", "5", "8.8.8.8"]
        imagePullPolicy: IfNotPresent
    - http:
        name: trigger-prometheus-snapshot
        collectorName: trigger-prometheus-snapshot
        namespace: '{{repl Namespace}}'
        post:
          url: http://rocketchat-prometheus:9090/api/v1/admin/tsdb/snapshot
          body: ''
          headers:
            Content-Type: "application/json"
    - exec:
        name: get-latest-prometheus-snapshot
        collectorName: get-latest-prometheus-snapshot
        namespace: '{{repl Namespace}}'
        selector:
          - app=rocketchat-prometheus
        command: ["bash"]
        args: ["-c", "cd /prometheus/data/snapshots && mv $(ls -t | head -n 1) latest"]
        timeout: 5s
    - copy:
        name: collect-prometheus-snapshot
        collectorName: collect-prometheus-snapshot
        selector:
          - app=rocketchat-prometheus
        namespace: '{{repl Namespace}}'
        containerPath: /prometheus/data/snapshots/latest
  analyzers:
    - textAnalyze:
        checkName: API Info
        fileName: api-info/result.json
        regex: 'success\\":true'
        outcomes:
          - pass:
              title: API Info
              message: Rocket.Chat API (/info) is properly responding.
          - fail:
              title: API Info
              message: Rocket.Chat API (/info) is not responding. RocketChat is probably not running as expected.



