apiVersion: troubleshoot.replicated.com/v1beta1
kind: SupportBundle
metadata:
  name: rocketchat-support-bundle
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        selector:
          - support=rocketchat
        namespace: default
        limits:
          maxAge: 720h
          maxLines: 1000
    - http:
        name: api-info
        get:
          url: http://rocketchat:3000/api/info
    - exec:
        name: mongo-version
        selector:
          - service=mongo
        namespace: default
        command: ["mongo"]
        args: ["--eval", "db.version()"]
        timeout: 5s
    - run:
        name: ping
        collectorName: "ping-google"
        image: busybox:1
        namespace: default
        command: ["ping"]
        args: ["-w", "5", "www.google.com"]
        imagePullPolicy: IfNotPresent
    - run:
        name: ping
        collectorName: "ping-google-dns-ip"
        image: busybox:1
        namespace: default
        command: ["ping"]
        args: ["-w", "5", "8.8.8.8"]
        imagePullPolicy: IfNotPresent
  analyzers:
    - textAnalyze:
        checkName: API Info
        fileName: api-info/result.json
        regex: 'success\\":true'
        outcomes:
          - pass:
              title: API Info
              message: Api info is properly responding.
          - fail:
              title: API Info
              message: Api info is not responding. RocketChat is probably not running as expected.



